fyers:
  access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiZDoxIiwiZDoyIiwieDowIiwieDoxIiwieDoyIl0sImF0X2hhc2giOiJnQUFBQUFCb1Q4cWpkNXU5cGdxbFBoWDFPWVZVeUh2dDE2czhTSE1INTVrd3VDSUVwazNVVVVFX2dVRHg1eEtXekY3cXN6QTBIdW5PMEFCRnpOOWlMVUNWMHNUcU11dEFIcEthdG00UW5xRmtqenlWYmFid0Vsdz0iLCJkaXNwbGF5X25hbWUiOiIiLCJvbXMiOiJLMSIsImhzbV9rZXkiOiI2YTczNTJjMTg5NWIwZjI4ZjBlNjMxNjU4ZWY2NzYwNjk5M2VlYTRkODEwYTM1ZTUwZTBiM2ZlOCIsImlzRGRwaUVuYWJsZWQiOiJOIiwiaXNNdGZFbmFibGVkIjoiTiIsImZ5X2lkIjoiWU0wNDA3NyIsImFwcFR5cGUiOjEwMCwiZXhwIjoxNzUwMTIwMjAwLCJpYXQiOjE3NTAwNTk2ODMsImlzcyI6ImFwaS5meWVycy5pbiIsIm5iZiI6MTc1MDA1OTY4Mywic3ViIjoiYWNjZXNzX3Rva2VuIn0.JXkCxxMkFD2wzrcES8zv9rUQtKUBzNPbZr6_UVIVCuk
  client_id: QZAWYQ69KZ-100
  redirect_uri: https://trade.fyers.in/api-login/redirect-uri/index.html
  secret_key: J02WG5J3V9
  token_expiry: '2025-06-17 13:11:23'
  totp_key: ''
logging:
  file: logs/strategy.log
  level: INFO
strategy:
  analysis_time: 09:20
  breakout_pct: 10
  max_holding_minutes: 30
  risk_reward_ratio: 2
  stoploss_pct: 20
  symbol: NSE:NIFTY50-INDEX
